In [84]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [85]:
df=pd.read_csv('train.csv')
df.head()

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
0,0,1,1017.4,21.2,20.6,19.9,19.4,87.0,88.0,1.1,60.0,17.2,1
1,1,2,1019.5,16.2,16.9,15.8,15.4,95.0,91.0,0.0,50.0,21.9,1
2,2,3,1024.1,19.4,16.1,14.6,9.3,75.0,47.0,8.3,70.0,18.1,1
3,3,4,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,60.0,35.6,1
4,4,5,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,40.0,24.8,0

In [86]:
df.describe()

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
count,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000,2190.000000
mean,1094.500000,179.948402,1013.602146,26.365799,23.953059,22.170091,20.454566,82.036530,75.721918,3.744429,104.863151,21.804703,0.753425
std,632.342866,105.203592,5.655366,5.654330,5.222410,5.059120,5.288406,7.800654,18.026498,3.626327,80.002416,9.898659,0.431116
min,0.000000,1.000000,999.000000,10.400000,7.400000,4.000000,-0.300000,39.000000,2.000000,0.000000,10.000000,4.400000,0.000000
25%,547.250000,89.000000,1008.600000,21.300000,19.300000,17.700000,16.800000,77.000000,69.000000,0.400000,40.000000,14.125000,1.000000
50%,1094.500000,178.500000,1013.000000,27.800000,25.500000,23.850000,22.150000,82.000000,83.000000,2.400000,70.000000,20.500000,1.000000
75%,1641.750000,270.000000,1017.775000,31.200000,28.400000,26.400000,25.000000,88.000000,88.000000,6.800000,200.000000,27.900000,1.000000
max,2189.000000,365.000000,1034.600000,36.000000,31.500000,29.800000,26.700000,98.000000,100.000000,12.100000,300.000000,59.500000,1.000000

In [87]:
df.isnull().sum()

id               0
day              0
pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
sunshine         0
winddirection    0
windspeed        0
rainfall         0
dtype: int64

In [88]:
features=['pressure','maxtemp','temparature','mintemp','dewpoint','humidity','cloud','sunshine','winddirection','windspeed']
X=df[features]
Y=df['rainfall']
X.head()

,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
0,1017.4,21.2,20.6,19.9,19.4,87.0,88.0,1.1,60.0,17.2
1,1019.5,16.2,16.9,15.8,15.4,95.0,91.0,0.0,50.0,21.9
2,1024.1,19.4,16.1,14.6,9.3,75.0,47.0,8.3,70.0,18.1
3,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,60.0,35.6
4,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,40.0,24.8

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.23, random_state=42)
X_train.head()

,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
979,1008.5,31.8,28.1,26.9,25.6,86.0,83.0,2.1,220.0,33.2
1061,1024.2,17.2,15.0,13.7,17.2,79.0,83.0,1.5,20.0,27.4
1444,1022.6,21.6,18.8,16.8,13.1,92.0,82.0,0.1,50.0,23.9
305,1015.3,28.9,26.6,23.5,23.5,85.0,88.0,2.0,80.0,9.8
209,1008.1,30.6,28.6,26.3,25.3,82.0,87.0,2.0,200.0,20.5

In [90]:
model1=LogisticRegression()
model1.fit(X_train,y_train)

y_pred=model1.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8591269841269841
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.61      0.69       129
           1       0.88      0.94      0.91       375

    accuracy                           0.86       504
   macro avg       0.83      0.78      0.80       504
weighted avg       0.85      0.86      0.85       504

Confusion Matrix:
 [[ 79  50]
 [ 21 354]]

c:\Users\simran dhillon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [91]:
model2=RandomForestClassifier()
model2.fit(X_train,y_train)

y_pred=model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8571428571428571
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.64      0.69       129
           1       0.88      0.93      0.91       375

    accuracy                           0.86       504
   macro avg       0.82      0.78      0.80       504
weighted avg       0.85      0.86      0.85       504

Confusion Matrix:
 [[ 82  47]
 [ 25 350]]

In [92]:
model3 = xgb.XGBClassifier(objective='binary:logistic', n_estimators=150, learning_rate=0.2, max_depth=17, random_state=42)
model3.fit(X_train, y_train)

y_pred_xgb = model3.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))

Accuracy: 0.8432539682539683
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.62      0.67       129
           1       0.88      0.92      0.90       375

    accuracy                           0.84       504
   macro avg       0.80      0.77      0.78       504
weighted avg       0.84      0.84      0.84       504

Confusion Matrix:
 [[ 80  49]
 [ 30 345]]

In [93]:
model4=KNeighborsClassifier(10)
model4.fit(X_train,y_train)

y_pred=model4.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8611111111111112
Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.67      0.71       129
           1       0.89      0.93      0.91       375

    accuracy                           0.86       504
   macro avg       0.83      0.80      0.81       504
weighted avg       0.86      0.86      0.86       504

Confusion Matrix:
 [[ 86  43]
 [ 27 348]]

In [94]:
df_f=pd.read_csv('test.csv')
x=df_f[features]

In [95]:
x.isnull().sum()

pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
sunshine         0
winddirection    1
windspeed        0
dtype: int64

In [96]:
x['winddirection'].fillna(x['winddirection'].mode()[0], inplace=True)

C:\Users\simran dhillon\AppData\Local\Temp\ipykernel_13272\3120199082.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x['winddirection'].fillna(x['winddirection'].mode()[0], inplace=True)
C:\Users\simran dhillon\AppData\Local\Temp\ipykernel_13272\3120199082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['winddirection'].fillna(x['winddirection'].mode()[0], inplace=True)

In [97]:
x.isnull().sum()

pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
sunshine         0
winddirection    0
windspeed        0
dtype: int64

In [98]:
df_f['rainfall']=model4.predict(x)
output=['id','rainfall']
df_f=df_f[output]
df_f.to_csv('submission.csv', index=False)